version: '2'

services:
    db:
        image: postgres
    redis:
        image: redis
    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - "./code:/galactic_empire"
        ports:
            - "3000:3000"
        depends_on:
            - db
            - redis
        user: "1000:1000"
