development: &default
    adapter: postgresql
    encoding: unicode
    database: galempire_dev
    pool: 5
    username: postgres
    password:
    host: db

test:
    <<: *default
    database: galempire_test
